version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  engine:
    build: ./engine
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  backend-api:
    build: ./backend-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # <--- DO NOT REMOVE THIS LINE
    depends_on:
      - backend-api
    environment:
      - WDS_SOCKET_PORT=0

