version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  engine:
    build: ./engine
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  backend-api:
    build: ./backend-api
    ports:
      - "0.0.0.0:8000:8000"
    stdin_open: true # Keeps the interactive session open
    tty: true        # Allocates a virtual terminal
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Important: Keeps container modules separate from host
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

